_id: "407841794726821888"
name: Learn
description: null
model: ""
createdAt: 2024-01-31T10:17:41.197Z
updatedAt: 2024-03-07T12:28:05.864Z
createdBy: z1hfptpNCvPcJwEoCVpgK5iq8dkn7uCad7E
updatedBy: z1hfptpNCvPcJwEoCVpgK5iq8dkn7uCad7E
pinnedAt: null
icon: https://bbqaz5tpm7zmfgc6s7p4urdkr7era7fj564f3goiqyy.did.abtnet.io/image-bin/uploads/937950d97affe8e93df7523e1cc65929.png
gitType: simple
temperature: 1
topP: 1
presencePenalty: null
frequencyPenalty: null
maxTokens: null
gitAutoSync: true
